project:
  type: website
  output-dir: docs
  resources:
   - static/
   - images/

website:
  title: ""
  google-analytics: "G-08NDRH85G1"  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Teaching
        menu: 
        - href: modelling.qmd
          text: Statistical Modelling
        - href: methods.qmd
          text: Research Crime & Justice
        - href: error.qmd
          text: Measurement Error 
        - href: missing.qmd
          text: Missing Data  
        - href: expert.qmd
          text: Expert Elicitation Techniques          
        - href: longitudinal.qmd
          text: Métodos Longitudinales
      - text: Research
        menu:
        - href: sentencing.qmd
          text: Sentencing
#        - href: sentencing_consistency.qmd
#          text: '   Sentencing: Consistency'          
#        - href: sentencing_punitiveness.qmd
#          text: '   Sentencing: Punitiveness'
#        - href: sentencing_guidelines.qmd
#          text: '   Sentencing: Guidelines'             
#        - href: sentencing_factors.qmd
#          text: '   Sentencing: Legal Factors' 
#        - href: sentencing_extralegal.qmd
#          text: '   Sentencing: Extra-legal Factors'           
#        - href: sentencing_opinion.qmd        
#          text: '   Sentencing: Public Opinion'            
        - href: disparities.qmd
          text: Disparities
#        - href: disparities_sentencing.qmd
#          text: '   Disparities: Sentencing'
#        - href: disparities_justice.qmd
#          text: '   Disparities: Criminal Justice'          
        - href: measurement.qmd
          text: Measurement
#        - href: measurement_crime.qmd
#          text: '   Measurement: Crime Data'
#        - href: measurement_retrospective.qmd
#          text: '   Measurement: Retrospective Data'
#        - href: measurement_other.qmd
#          text: '   Measurement: Other'          
        - href: crime.qmd
          text: Causes of Crime
        - href: procedural.qmd
          text: Procedural Justice
        - href: cars.qmd
          text: Car Dependency
        - href: meta.qmd
          text: Meta Science          
        - href: failed.qmd
          text: Failed Projects
      - href: presentations.qmd
        text: Presentations           
      - href: impact.qmd
        text: Impact   
      - href: service.qmd
        text: Service         
      - href: outreach.qmd
        text: Outreach          
      - href: rants.qmd
        text: Rants

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    embed-resources: true
    html-math-method: katex
    execute:
      allowjs: true    

editor: visual

