project:
  type: website
  output-dir: docs
  resources:
   - static/
   - images/

website:
  title: ""
  google-analytics: "G-08NDRH85G1"  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Teaching
        menu: 
        - href: modelling.qmd
          text: Statistical Modelling
        - href: methods.qmd
          text: Research Crime & Justice
        - href: error.qmd
          text: Measurement Error 
        - href: missing.qmd
          text: Missing Data  
        - href: expert.qmd
          text: Expert Elicitation Techniques          
        - href: longitudinal.qmd
          text: Métodos Longitudinales
        - href: sentencias.qmd
          text: Análisis de Sentencias         
      - text: Research
        menu:
        - href: sentencing.qmd
          text: Sentencing
        - href: disparities.qmd
          text: Disparities
        - href: measurement.qmd
          text: Measurement
        - href: crime.qmd
          text: Causes of Crime
        - href: procedural.qmd
          text: Procedural Justice
        - href: cars.qmd
          text: Cars & Crime
        - href: meta.qmd
          text: Meta Science          
        - href: failed.qmd
          text: Failed Projects
      - href: impact.qmd
        text: Impact   
      - href: service.qmd
        text: Service         
      - href: outreach.qmd
        text: Outreach          
      - href: rants.qmd
        text: Rants

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    embed-resources: true
    html-math-method: katex
    execute:
      allowjs: true    

editor: visual

