---
title: "Rants"
---

------------------------------------------------------------------------

Here's a curated list of my favourite rants, so you can see how I waste time being annoying on social media. I find it quite cathartic, though, so I'll probably keep it a while longer.

<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:e73x2agpxzjezxw3acygrvyr/app.bsky.feed.post/3mtgvgoym722u" data-bluesky-cid="bafyreicbei6gsstq4u2pa5od36a5ya6wk5vnbazlarlq4kig4uduk7nd7u"><p lang="en">Latest update from the dystopian world of academic publishing: Springer Nature and BMC (also owned by Springer Nature) appear to be spending a fortune on YouTube ads to attract submissions to their journals. No wonder APCs run into the thousands. What a great use of research funding. #OpenScience<br><br><a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3mtgvgoym722u?ref_src=embed">[image or embed]</a></p>&mdash; Jose Pina-Sánchez 🇪🇺 (<a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr?ref_src=embed">@jpinasanchez.eurosky.social</a>) <a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3mtgvgoym722u?ref_src=embed">15:02 · Aug 19, 2026</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>

<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:e73x2agpxzjezxw3acygrvyr/app.bsky.feed.post/3mskpgwocqk27" data-bluesky-cid="bafyreiavsvfklomd5jms4slaql35dghsyfz4bkvggtp763hlxtqmz6ra3q" data-bluesky-embed-color-mode="light"><p lang="en">When asked why I hate cars so much I tend to point at the multiple harms they inflict: pollution, collisions, degradation of the public space, etc. However, when I&#x27;m back in Tres Cantos (Madrid), where I grew up, I wonder whether those answers are just the rationalisation of a lost sense of serenity<br><br><a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3mskpgwocqk27?ref_src=embed">[image or embed]</a></p>&mdash; Jose Pina-Sánchez 🇪🇺 (<a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr?ref_src=embed">@jpinasanchez.eurosky.social</a>) <a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3mskpgwocqk27?ref_src=embed">10:00 · Aug 8, 2026</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>

<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:e73x2agpxzjezxw3acygrvyr/app.bsky.feed.post/3m2lpw2jkuc25" data-bluesky-cid="bafyreie4bp3mxr2jogecr5iwcv4dcqdee6cuxmjigmojnegwnzvjx2cpsi">

<p lang="en">

"The public are sick of voting for tougher sentences and getting the opposite." www.theguardian.com/law/2025/oct... To put it mildly, Robert Jenrick is a complete imbecile who does not know what he is talking about: www.sentencingacademy.org.uk/wp-content/u...<br><br><a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3m2lpw2jkuc25?ref_src=embed">\[image or embed\]</a>

</p>

— Jose Pina-Sánchez 🇪🇺 (<a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr?ref_src=embed">@jpinasanchez.bsky.social</a>) <a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3m2lpw2jkuc25?ref_src=embed">October 7, 2025 at 9:36 AM</a>

</blockquote>

```{=html}
<script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
```

<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:e73x2agpxzjezxw3acygrvyr/app.bsky.feed.post/3lyfny5ktp22h" data-bluesky-cid="bafyreifccfmm32cnw6tl7dur24t4cibjiew4r42lrcikw4otnxvvgrlmba">

<p lang="en">

This is a question I need to get right (I cannot say "Avoid using GenAI at all to eliminate any risks of mistakes") in order to complete the compulsory training on GenAI required at work. I'm not anti Ai, I find it useful for tasks like coding and proofreading, but this feels like forcing it.<br><br><a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3lyfny5ktp22h?ref_src=embed">\[image or embed\]</a>

</p>

— Jose Pina-Sánchez 🇪🇺 (<a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr?ref_src=embed">@jpinasanchez.bsky.social</a>) <a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3lyfny5ktp22h?ref_src=embed">September 9, 2025 at 12:55 PM</a>

</blockquote>

```{=html}
<script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
```

<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:e73x2agpxzjezxw3acygrvyr/app.bsky.feed.post/3lsjnrfe7fc2x" data-bluesky-cid="bafyreign7yrmsa7emrclq4tyvpaxcfxgaa4kvfdn4limtrz3twskmc2wwa">

<p lang="en">

This goes on my epitaph: "Professor Jose Pino Sanchez said in his presentation that research ought to be 'unbias' and implied that knowledge should have a statistically verifiable basis for it to be acceptable. This is quite disrespectful towards qualitative researchers..."

</p>

— Jose Pina-Sánchez 🇪🇺 (<a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr?ref_src=embed">@jpinasanchez.bsky.social</a>) <a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3lsjnrfe7fc2x?ref_src=embed">June 26, 2025 at 6:31 PM</a>

</blockquote>

```{=html}
<script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
```

<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:e73x2agpxzjezxw3acygrvyr/app.bsky.feed.post/3lrfc26535k27" data-bluesky-cid="bafyreihqwrqvelphdewgy55mfezlwc7t655dvopjfdyp5n5wmlgxo6oqem">

<p lang="en">

'Engaging researchers in conversations about the impact of their publishing choices'. This is quite funny. The general public finds academics insufferable in how we love pontificating about everything, yet when it comes to our own practices, we are as innocent and oblivious as little babies. 🙈🙉🙊<br><br><a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3lrfc26535k27?ref_src=embed">\[image or embed\]</a>

</p>

— Jose Pina-Sánchez 🇪🇺 (<a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr?ref_src=embed">@jpinasanchez.bsky.social</a>) <a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3lrfc26535k27?ref_src=embed">Jun 12, 2025 at 07:25</a>

</blockquote>

```{=html}
<script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
```

<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:e73x2agpxzjezxw3acygrvyr/app.bsky.feed.post/3lnwvwt6jzk2c" data-bluesky-cid="bafyreifa6vwlhd4btfz7ptoragpjd5227otftnunljvkavbefliuprp6q4">

<p lang="en">

Piece of advice to anyone thinking of submitting an article to 'The European Journal of Psychology Applied to Legal Context', DO NOT preregister your analytical strategy or preprint the paper. It seems that sets out a 'similarity check' alarm, 67% similarity in my case, #DeskRejected, #OpenScience

</p>

— Jose Pina-Sánchez 🇪🇺 (<a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr?ref_src=embed">@jpinasanchez.bsky.social</a>) <a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3lnwvwt6jzk2c?ref_src=embed">April 29, 2025 at 9:56 AM</a>

</blockquote>

```{=html}
<script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
```

<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:e73x2agpxzjezxw3acygrvyr/app.bsky.feed.post/3lna3qtwnmk2z" data-bluesky-cid="bafyreif3sg65qsspqaqcv5jommmvrizlrkd2qdcwqbossrlxdlldhwdipa">

<p lang="en">

Crazy idea: when evaluating candidates for academic jobs or promotions, what if we set aside citations, grants, REF\*, impact factors, keynotes, social media followers… and just read their work?<br><br><a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3lna3qtwnmk2z?ref_src=embed">\[image or embed\]</a>

</p>

— Jose Pina-Sánchez 🇪🇺 (<a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr?ref_src=embed">@jpinasanchez.bsky.social</a>) <a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3lna3qtwnmk2z?ref_src=embed">April 20, 2025 at 8:09 AM</a>

</blockquote>

```{=html}
<script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
```

<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:e73x2agpxzjezxw3acygrvyr/app.bsky.feed.post/3ljheidh2f22l" data-bluesky-cid="bafyreid4476prvnu7f6unaggou3wv2cvsyna4sy7kzuynj6asiaqflgvei">

<p lang="en">

#ResearchFish, by far the most effective strategy deployed by #UKRI to limit the number of grant applications.

</p>

— Jose Pina-Sánchez 🇪🇺 (<a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr?ref_src=embed">@jpinasanchez.bsky.social</a>) <a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3ljheidh2f22l?ref_src=embed">March 3, 2025 at 6:53 AM</a>

</blockquote>

```{=html}
<script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
```

<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:e73x2agpxzjezxw3acygrvyr/app.bsky.feed.post/3lht2xh5n7c27" data-bluesky-cid="bafyreic7hevgedwcbo2k7yc2sv5aiihyluhledmll6wsx76myqg7ezjmiu">

<p lang="en">

#Criminologists, #LegalResearchers, it is going to look very weird if we end up being the last to do the right thing.<br><br><a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3lht2xh5n7c27?ref_src=embed">\[image or embed\]</a>

</p>

— Jose Pina-Sánchez 🇪🇺 (<a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr?ref_src=embed">@jpinasanchez.bsky.social</a>) <a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3lht2xh5n7c27?ref_src=embed">February 10, 2025 at 11:44 AM</a>

</blockquote>

```{=html}
<script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
```

<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:e73x2agpxzjezxw3acygrvyr/app.bsky.feed.post/3lg2a4tchc22y" data-bluesky-cid="bafyreiaqfjlmkwznhkgwerlxdufxud2fd3lkv44b2gtatrbirf3o6zjdt4">

<p lang="en">

This feels like we are about to do The Hunger Games, UK higher education version. So unbelievably out of touch with the reality that our sector is experiencing. Anyway, may the odds be in our favour.<br><br><a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3lg2a4tchc22y?ref_src=embed">\[image or embed\]</a>

</p>

— Jose Pina-Sánchez 🇪🇺 (<a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr?ref_src=embed">@jpinasanchez.bsky.social</a>) <a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3lg2a4tchc22y?ref_src=embed">January 18, 2025 at 9:15 PM</a>

</blockquote>

```{=html}
<script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
```

<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:e73x2agpxzjezxw3acygrvyr/app.bsky.feed.post/3lfsg5n5wrs2m" data-bluesky-cid="bafyreichfxetkfxamb2drhitesj5kvlpekhq3arihdogydeq4bfsoxfwmu">

<p lang="en">

The back of #Leeds Civic Hall, one of the most beautiful plazas I’ve seen anywhere, a true hidden jewel in the middle of the city, completely ruined by using it as a parking lot. Come on @leedscitycouncil.bsky.social do the right thing. #WarOnCars<br><br><a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3lfsg5n5wrs2m?ref_src=embed">\[image or embed\]</a>

</p>

— Jose Pina-Sánchez 🇪🇺 (<a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr?ref_src=embed">@jpinasanchez.bsky.social</a>) <a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3lfsg5n5wrs2m?ref_src=embed">January 15, 2025 at 6:41 PM</a>

</blockquote>

```{=html}
<script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
```

<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:e73x2agpxzjezxw3acygrvyr/app.bsky.feed.post/3lfm6tg3voc2n" data-bluesky-cid="bafyreiccosogcyfodrabb3wnkz4iqlo2ma74cb4pawdr2tpaobovtmhwbu">

<p lang="en">

Lastly, this research was made possible by new administrative data from the #MoJ, provided by the #DataFirst team, for which we are grateful. However, working with this data was a bit of a nightmare due to excessive gatekeeping by the #ONS, #MoJ, and #JudicialOffice, leading to multiple delays.

</p>

— Jose Pina-Sánchez 🇪🇺 (<a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr?ref_src=embed">@jpinasanchez.bsky.social</a>) <a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3lfm6tg3voc2n?ref_src=embed">January 13, 2025 at 7:14 AM</a>

</blockquote>

```{=html}
<script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
```

<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:e73x2agpxzjezxw3acygrvyr/app.bsky.feed.post/3lfh5iggqr22l" data-bluesky-cid="bafyreife2m3imq4ofeimd3gdwwnmzr7dez2i74gilj6gbdaerdqgybutqq">

<p lang="en">

Academics enthusiastically sharing their latest research as '#OpenAccess', while omitting the fact that their universities pay thousands in fees to make it so.<br><br><a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3lfh5iggqr22l?ref_src=embed">\[image or embed\]</a>

</p>

— Jose Pina-Sánchez 🇪🇺 (<a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr?ref_src=embed">@jpinasanchez.bsky.social</a>) <a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3lfh5iggqr22l?ref_src=embed">January 11, 2025 at 7:07 AM</a>

</blockquote>

```{=html}
<script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
```

<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:e73x2agpxzjezxw3acygrvyr/app.bsky.feed.post/3lfaqugeagc2p" data-bluesky-cid="bafyreig46dowyc4wrjvoirx2mineol7ljknoaq43wezdmnun22gaume7x4">

<p lang="en">

I’ve just resigned from the editorial boards of a couple of for-profit journals. From now on, I’ll only review and write (when I am the first author) for Diamond #OpenAccess journals. Being part of the current system felt increasingly hypocritical. www.researchprofessionalnews.com/rr-news-uk-u...<br><br><a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3lfaqugeagc2p?ref_src=embed">\[image or embed\]</a>

</p>

— Jose Pina-Sánchez 🇪🇺 (<a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr?ref_src=embed">@jpinasanchez.bsky.social</a>) <a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3lfaqugeagc2p?ref_src=embed">January 8, 2025 at 6:05 PM</a>

</blockquote>

```{=html}
<script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
```

<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:e73x2agpxzjezxw3acygrvyr/app.bsky.feed.post/3leygmuvyek2p" data-bluesky-cid="bafyreiavffqxfqxy6goknfrhe5gkvzwov4tecnxovcfhs4jufitowyo4yy">

<p lang="en">

Got an email to renew my membership to the European Society of Criminology. As much as I’ve enjoyed #ESC conferences in the past, I’ll give it a pass this year. Seems weird that 1/6 of fees go to the Executive Secretariat, a seemingly permanent role held by the same person/s in perpetuity.<br><br><a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3leygmuvyek2p?ref_src=embed">\[image or embed\]</a>

</p>

— Jose Pina-Sánchez 🇪🇺 (<a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr?ref_src=embed">@jpinasanchez.bsky.social</a>) <a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3leygmuvyek2p?ref_src=embed">January 5, 2025 at 10:40 AM</a>

</blockquote>

```{=html}
<script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
```

<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:e73x2agpxzjezxw3acygrvyr/app.bsky.feed.post/3ld42qtmsak2g" data-bluesky-cid="bafyreierbfvqjldum36man5ygt6cj3wk4nmkqzpt3qe2ottn4ljep2kz2e">

<p lang="en">

This is crucial, but also directly incompatible with the #REF. It is just not possible to honestly convey the uncertainty of your findings, while simultaneously highlight the 'world leading' impact of your paper. Especially if overhyping is common practice in your field.<br><br><a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3ld42qtmsak2g?ref_src=embed">\[image or embed\]</a>

</p>

— Jose Pina-Sánchez 🇪🇺 (<a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr?ref_src=embed">@jpinasanchez.bsky.social</a>) <a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3ld42qtmsak2g?ref_src=embed">December 12, 2024 at 10:28 AM</a>

</blockquote>

```{=html}
<script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
```

<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:eyadq5f6fwszd5sig7o4zlst/app.bsky.feed.post/3lcnd4j4n5s24" data-bluesky-cid="bafyreigqu4oku466av5xgqhoy6mycnanueq5c3gdv4s6eberbro6jnkxqa">

<p lang="en">

I would go a bit farther... Should we really support scientific societies that have official journals that aren't diamond? What does it say about us as an organised collective that we let our societies to contribute to the problem instead of being part of the solution?

</p>

— Juanjo Medina (<a href="https://bsky.app/profile/did:plc:eyadq5f6fwszd5sig7o4zlst?ref_src=embed">@jjmedina.bsky.social</a>) <a href="https://bsky.app/profile/did:plc:eyadq5f6fwszd5sig7o4zlst/post/3lcnd4j4n5s24?ref_src=embed">December 6, 2024 at 1:48 PM</a>

</blockquote>

```{=html}
<script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
```

<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:e73x2agpxzjezxw3acygrvyr/app.bsky.feed.post/3lcn2s4f6yc2y" data-bluesky-cid="bafyreiavicjccoszv2mw4hawvd73dwnzwuxh4szu43dfwidswdmyths23q">

<p lang="en">

Does anyone know how much do UK universities pay to make papers published by their staff in Wiley journals #OpenAccess? authorservices.wiley.com/author-resou... If this is in the thousands, should not we make it a top priority to change this system and publish only in diamond open access journals?<br><br><a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3lcn2s4f6yc2y?ref_src=embed">\[image or embed\]</a>

</p>

— Jose Pina-Sánchez 🇪🇺 (<a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr?ref_src=embed">@jpinasanchez.bsky.social</a>) <a href="https://bsky.app/profile/did:plc:e73x2agpxzjezxw3acygrvyr/post/3lcn2s4f6yc2y?ref_src=embed">December 6, 2024 at 11:19 AM</a>

</blockquote>

```{=html}
<script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
```
